dictionaries_keys_in_idTrackerDeep = {
    'dfGlobal': ,
    'fragments': {'framesAndBlobColumns': 'list of lists of nx2 arrays where n is the len of the individual fragment in a complete fragment. The first column is the frame and the second column is the column of the blob',
                'minDistIndivCompleteFragments':'list of the minimum length of the individuals fragments of a complete fragment',
                'oneIndivFragLens',
                'oneIndivFragSumLens',
                'oneIndivFragIntervals',
                'oneIndivFragFrames',
                'oneIndivFragDists',
                'oneIndivFragVels',
                'intervals',
                'minLenIndivCompleteFragments',
                'fragments':'list of global fragments',
                'intervalsDist',
                'framesAndBlobColumnsDist'}}
